version: '3.8'
services:
   web:
       image: aruko/firstdockerfile:latest
       command: bash -c "python src/app.py && pytest tests -W ignore::DeprecationWarning"
       ports:
           - 5000:5000